name: Laravel

on:
  push:
    branches: [ master ]  

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: APP_DEBUG=0 composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install NPM install
      run: npm install
           npm run dev
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Docker build image
      run: docker build -t "laravel-nginx-mysql:master" .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker Push Image
      run: docker push "laravel-nginx-mysql:master"
